/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-16 05:33:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Home.jsp", out, false);
      out.write("<br /><br />\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>공지사항</title>\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("        function check() {\r\n");
      out.write("                if(document.myform.b_name.value.length==0) {\r\n");
      out.write("                        alert(\"이름을 써주세요\");\r\n");
      out.write("                        myform.w_name.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.myform.b_title.value.length==0) {\r\n");
      out.write("                        alert(\"제목을 써주세요.\");\r\n");
      out.write("                        myform.b_title.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.myform.b_content.value.length==0) {\r\n");
      out.write("                        alert(\"내용을 써주세요.\");\r\n");
      out.write("                        myform.b_content.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.myform.b_pwd.value.length==0) {\r\n");
      out.write("                        alert(\"수정시 필요한 비밀번호를 써주세요.\");\r\n");
      out.write("                        myform.b_pwd.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                document.myform.submit();\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"white\" text=\"black\" link=\"blue\" vlink=\"red\" alink=\"red\">\r\n");
      out.write("\r\n");
      out.write("<p align=\"center\"><font color=\"#00000\" size=\"30\"><font size=\"30\"></font><b>공지 사항</b></font> \r\n");
      out.write("<table border=\"1\" cellpadding=\"4\" align=\"center\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#00000\"><p align=\"center\"><font size=\"2\" color=\"white\">이 \r\n");
      out.write("            름</font></td>\r\n");
      out.write("        <td width=\"645\" style=\"text-align:left;\"><form name=\"myform\" method=\"post\" action=write_act1.jsp>\r\n");
      out.write("            <p><input type=\"text\" name=\"b_name\" maxlength=\"10\" size=\"10\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#00000\"><p align=\"center\"><font size=\"2\" color=\"white\">전자우편\r\n");
      out.write("</font></td>\r\n");
      out.write("        <td width=\"645\" style=\"text-align:left;\"><p><input type=\"text\" name=\"b_mail\" maxlength=\"30\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#00000\"><p align=\"center\"><font size=\"2\" color=\"white\">제 \r\n");
      out.write("            목</font></td>\r\n");
      out.write("        <td width=\"645\" style=\"text-align:left;\"><p><input type=\"text\" name=\"b_title\" maxlength=\"60\" \r\n");
      out.write("size=\"40\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#00000\"><p align=\"center\"><font size=\"2\" color=\"white\">내 \r\n");
      out.write("            용</font></td>\r\n");
      out.write("        <td width=\"645\" style=\"text-align:left;\"><p><textarea name=\"b_content\" rows=\"5\" \r\n");
      out.write("cols=\"40\"></textarea></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#00000\"><p align=\"center\"><font size=\"2\" color=\"white\">비밀번호\r\n");
      out.write("</font></td>\r\n");
      out.write("        <td width=\"645\" style=\"text-align:left;\"><p><input type=\"password\" name=\"b_pwd\" maxlength=\"12\"\r\n");
      out.write("             size=\"9\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<p><input type=\"button\" value=\"글올리기\" onclick=\"check()\"> <input\r\n");
      out.write(" type=\"reset\" value=\"다시쓰기\">\r\n");
      out.write("</p></form>\r\n");
      out.write("<a href=\"list1.jsp\"> 목록으로 </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
