/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-16 05:33:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class modify1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

        String b_name=null,b_mail=null,b_title=null,b_content=null;
        String b_id=request.getParameter("b_id");

        Class.forName("com.mysql.jdbc.Driver"); 

        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","dkwl12"); 

        Statement stmt= conn.createStatement();
	String sql="select b_name,b_mail,b_title,b_content from board where b_id="+b_id;
        ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()) {
                        b_name=rs.getString(1);
                        b_mail=rs.getString(2);
                        b_title=rs.getString(3);
                        b_content=rs.getString(4);
                }       
        rs.close();
        stmt.close();
        conn.close();   

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Home.jsp", out, false);
      out.write("</br></br>\r\n");
      out.write("<title>수정하기</title>\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("        function check() {\r\n");
      out.write("                if(document.form.b_name.value.length==0) {\r\n");
      out.write("                        alert(\"이름을 써주세요\");\r\n");
      out.write("                        form.b_name.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.form.b_title.value.length==0) {\r\n");
      out.write("                        alert(\"제목을 써주세요.\");\r\n");
      out.write("                        form.b_title.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.form.b_content.value.length==0) {\r\n");
      out.write("                        alert(\"내용을 써주세요.\");\r\n");
      out.write("                        form.b_content.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.form.b_pwd.value.length==0) {\r\n");
      out.write("                        alert(\"수정시 필요한 비밀번호를 써주세요.\");\r\n");
      out.write("                        form.b_pwd.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                }\r\n");
      out.write("                document.form.submit();\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"white\" text=\"black\" link=\"blue\" vlink=\"red\" alink=\"red\" style=\"font-family:돋움;\">\r\n");
      out.write("<center>\r\n");
      out.write("<p align=\"center\"><font color=\"#00000\" size=\"70\"><font size=\"70\"></font><b>수정하기</b><br><br><br></font>\r\n");
      out.write("<table border=\"1\" cellpadding=\"1\" width=\"900\" height=\"350\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#000000\"><p align=\"center\"><font size=\"2\" color=\"white\">이 \r\n");
      out.write("            름</font></td>\r\n");
      out.write("        <td width=\"645\"><form name=\"form\" method=\"post\" action=modify_act1.jsp>\r\n");
      out.write("            <p><input type=\"text\" name=\"b_name\" maxlength=\"20\" size=\"20\" value=\"");
      out.print(b_name);
      out.write("\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#000000\"><p align=\"center\"><font size=\"2\" color=\"white\">전자우편</font></td>\r\n");
      out.write("        <td width=\"645\"><p><input type=\"text\" name=\"b_mail\" maxlength=\"30\" value=\"");
      out.print(b_mail);
      out.write("\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#000000\"><p align=\"center\"><font size=\"2\" color=\"white\">제 \r\n");
      out.write("            목</font></td>\r\n");
      out.write("        <td width=\"645\"><p><input type=\"text\" name=\"b_title\" maxlength=\"60\" size=\"40\" value=\"");
      out.print(b_title);
      out.write("\"></td\r\n");
      out.write(">\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#000000\"><p align=\"center\"><font size=\"2\" color=\"white\">내 \r\n");
      out.write("            용</font></td>\r\n");
      out.write("        <td width=\"645\"><p><textarea name=\"b_content\" rows=\"5\" cols=\"40\">");
      out.print(b_content);
      out.write("</textarea></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"89\" bgcolor=\"#000000\"><p align=\"center\"><font size=\"2\" color=\"white\">비밀번호</font></td>\r\n");
      out.write("        <td width=\"645\"><p><input type=\"password\" name=\"b_pwd\" maxlength=\"12\"\r\n");
      out.write("             size=\"9\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<input type=hidden name=b_id value=\"");
      out.print(b_id);
      out.write("\">\r\n");
      out.write("<input type=\"button\" value=\"수정하기\" onclick=\"check()\">&nbsp;<input type=\"reset\" value=\"다시쓰기\">\r\n");
      out.write("<p>\r\n");
      out.write("<a href=\"list1.jsp\"> 목록으로 </a>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html> \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
