/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-16 04:27:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>대한민국 치안 방지 프로젝트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tfont: bold 15px/1.5em 맑은 고딕, Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("\tfont: bold 80px 맑은 고딕, Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tmargin: 26px;\r\n");
      out.write("\tpadding: 0px 0px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*- Menu Tabs E--------------------------- */\r\n");
      out.write("#tabsE {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground: #000;\r\n");
      out.write("\tfont-size: 150%;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE ul {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\t/* padding:10px 10px 0 50px; */\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE li {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground: url(\"tableftE.gif\") no-repeat left top;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0 0 0 4px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE a span {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tbackground: url(\"tabrightE.gif\") no-repeat right top;\r\n");
      out.write("\tpadding: 5px 15px 4px 6px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("}\r\n");
      out.write("/* Commented Backslash Hack hides rule from IE5-Mac \\*/\r\n");
      out.write("#tabsE a span {\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("}\r\n");
      out.write("/* End IE5-Mac hack */\r\n");
      out.write("#tabsE a:hover span {\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE a:hover {\r\n");
      out.write("\tbackground-position: 0% -42px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE a:hover span {\r\n");
      out.write("\tbackground-position: 100% -42px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE #current a {\r\n");
      out.write("\tbackground-position: 0% -42px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabsE #current a span {\r\n");
      out.write("\tbackground-position: 100% -42px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("--> /* 게시판 css */\r\n");
      out.write("table {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tborder-bottom-color: #000;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:first-child {\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead {\r\n");
      out.write("\tbackground-color: #f4f4f4; /* border-bottom:1px solid #f4f4f4; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:first-child th {\r\n");
      out.write("\tbackground: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:first-child th p font {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("tbody tr:not(:FIRST-CHILD){\r\n");
      out.write("\tborder-bottom: 1px solid #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:not(:first-child) th p a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h2 style=\"text-align: center;\">SAFEME 모니터링 서비스</h2>\r\n");
      out.write("\t<div id=\"tabsE\" style=\"text-align:center; margin:0 atuo;\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<!-- CSS Tabs -->\r\n");
      out.write("\t\t\t<li><a href=\"HomeImage.jsp\"><span>홈</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"recordkesipan.jsp\"><span>녹화된 신고물</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"sinkokyesipan.jsp\"><span>신고게시판</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"list1.jsp\"><span>공지사항</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
