/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-16 05:31:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class list1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Home.jsp", out, false);
      out.write("</br></br>\r\n");
      out.write("<title>글 목록 보기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"white\" text=\"black\" link=\"blue\" vlink=\"red\" alink=\"red\">\r\n");
      out.write("<p align=\"center\"><br>\r\n");
      out.write("<div align=\"center\"><h1>공지사항</h1>\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"1000\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td bgcolor=\"black\"><table border=\"0\" cellpadding=\"5\" cellspacing=\"3\" width=\"100%\">\r\n");
      out.write("<!-- 검색기 추가 -->\r\n");
      out.write("<div text-align=\"center\" style=\"margin-bottom:20px;\">\r\n");
      out.write("<form method=\"post\" action=\"search_result.jsp\">\r\n");
      out.write("<select name=\"search\">\r\n");
      out.write("<option value=\"b_name\">글쓴 이</option>\r\n");
      out.write("<option value=\"b_title\">글 제목</option>\r\n");
      out.write("<option value=\"b_content\">글 내용</option></select>\r\n");
      out.write("<input type=\"text\" name=\"keyword\" size=\"12\">\r\n");
      out.write("<input type=\"submit\" value=\"검색\">\r\n");
      out.write("</form>\r\n");
      out.write("<!-- 검색기 끝 -->\r\n");
      out.write("</div>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th align=\"center\" nowrap bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                         size=\"2\" color=black>번호</font></th>\r\n");
      out.write("                    <th width=\"500\" align=\"center\" nowrap bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                         size=\"2\" color=black>제 목</font></th>\r\n");
      out.write("                    <th width=114 align=\"center\" nowrap bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                         size=\"2\" color=black>이름</font></th>\r\n");
      out.write("                    <th width=\"114\" align=\"center\" nowrap bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                         size=\"2\" color=black>날짜</font></th>\r\n");
      out.write("                    <th align=\"center\" nowrap bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                         size=\"2\" color=black>조회</font></th>\r\n");
      out.write("                </tr>\r\n");

try {
        String b_name,b_mail,b_title,b_content,b_date,b_pwd,mailtoyou;
        int b_id,b_view;

	int datacount=0;  
        int pagecount;

      Class.forName("com.mysql.jdbc.Driver"); 
      Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/safemetest","root","test123"); 
      Statement stmt = conn.createStatement();  

      System.out.println("count : "+datacount);
        ResultSet rs0=stmt.executeQuery("select count(b_id) from board");
        if(rs0.next()) {
                datacount=rs0.getInt(1); 
                rs0.close();
        }
        int pagesize=10;
        pagecount=datacount/(pagesize+1)+1;  
        int mypage=1;
        int abpage=1;  
        if(request.getParameter("mypage")!=null) {
                mypage=Integer.parseInt(request.getParameter("mypage"));
                abpage=(mypage-1)*pagesize+1;
		if(abpage <= 0 ) abpage=1;
        }

       ResultSet rs = stmt.executeQuery("select b_id,b_name,b_mail,b_title,b_content,date_format(b_date,'%Y-%m-%d'),b_view,b_pwd from board order by b_id desc");

	if(!rs.next()) {  
		pagesize=0;
	} else {
		rs.absolute(abpage);
	}
	for(int k=1;k <= pagesize; k++) {  
                b_id=rs.getInt(1);
                b_name=rs.getString(2);
                b_mail=rs.getString(3);
                b_title=rs.getString(4);
                b_content=rs.getString(5);
                b_date=rs.getString(6);
                b_view=rs.getInt(7);
                b_pwd=rs.getString(8);
                if(!b_mail.equals("")) {
                        mailtoyou="<a href=mailto:"+b_mail+">"+b_name+"</a>";
                } else {
                        mailtoyou=b_name;
                }

      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td align=\"center\" bgcolor=\"#FFFFFF\" ><p><font size=\"2\">");
      out.print(b_id);
      out.write("</font></td>\r\n");
      out.write("                  <td width=\"364\" align=\"left\" bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                       size=\"2\">&nbsp;&nbsp;&nbsp;</font><a href=\"view1.jsp?bid=");
      out.print(b_id);
      out.write("\"><font\r\n");
      out.write("                       size=\"2\">");
      out.print(b_title);
      out.write("</font></a></td>\r\n");
      out.write("                  <td width=\"94\" align=\"center\" nowrap bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                       size=\"2\">");
      out.print(mailtoyou);
      out.write("</font></td>\r\n");
      out.write("                  <td width=\"114\" align=\"center\" bgcolor=\"#FFFFFF\"><p><font\r\n");
      out.write("                       size=\"2\">");
      out.print(b_date);
      out.write("</font></td>\r\n");
      out.write("                  <td align=\"center\" bgcolor=\"#FFFFFF\" ><p><font size=\"2\">");
      out.print(b_view);
      out.write("</font></td>\r\n");
      out.write("                </tr>\r\n");

		if(rs.getRow()==datacount){  
			break;
		} else {
			rs.next();
		}
	} 

	rs.close();
	stmt.close(); 
	conn.close(); 


      out.write("\r\n");
      out.write("            </table></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table></div><br>\r\n");
      out.write("<p align=\"center\"><font size=2>\r\n");

        int gopage=1;
        if(mypage!=1) {
                gopage=mypage-1;
                out.println("<a href=list1.jsp?mypage="+gopage+"><<이전</a>  ");
        } else {
		out.println("<<이전");
	}

      out.write('\r');
      out.write('\n');

        if(mypage!=pagecount) {
                gopage=mypage+1;
                out.println("<a href=list1.jsp?mypage="+gopage+">다음>></a>  ");
        } else {
		out.println("다음>>");
	}
} catch (Exception e) {
	out.println(e);
}

      out.write("\r\n");
      out.write("<p align=center><font size=2><a href=\"write1.jsp\">글쓰기</a></font></p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
