/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-16 04:31:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class recordkesipan_005fview1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Home.jsp", out, false);
      out.write("</br>\r\n");
      out.write("</br>\r\n");
      out.write("<style>\r\n");
      out.write("tbody tr:hover {\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-bottom: 1px solid #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>녹화된 영상</title>\r\n");
      out.write("<script src=\"../js/jquery-1.11.3.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jwplayer.js\"></script>\r\n");
      out.write("<script src=\"../js/player.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tjwplayer.key = \"2k/OWiKCBtXbD9wRCh1hiuF5tCfq8UV1y7Vgfw==\"\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"white\" text=\"black\" link=\"blue\" vlink=\"red\" alink=\"red\">\r\n");
      out.write("\t");

		try {
			String b_date, b_time, b_phonenum, b_filename, b_loc_str, b_loc_lat, b_loc_lon;
			int b_id;

			String bid = request.getParameter("bid");

			Class.forName("com.mysql.jdbc.Driver");

			Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/safemetest", "root",
					"test123");

			Statement stmt = conn.createStatement();
			String sql = "select * from notify where id=" + bid;
			ResultSet rs = stmt.executeQuery(sql);
			if (rs.next()) {
				b_id = rs.getInt(1);
				b_date = rs.getString(2);
				b_time = rs.getString(3);
				b_phonenum = rs.getString(4);
				b_filename = rs.getString(5);
				b_loc_str = rs.getString(6);
				b_loc_lat = rs.getString(7);
				b_loc_lon = rs.getString(8);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<h1>파일 내용</h1>\r\n");
      out.write("\t\t<table border=\"1\" cellpadding=\"1\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t<table bgcolor=\"#FFFFFF\" border=\"1\" cellpadding=\"2\" cellspacing=\"1\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 700px; table-layout: fixed;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th align=\"center\" bgcolor=\"#FFFFFF\" style=\"width: 30%; height: 50px;\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\">파일이름<br></font></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#FFFFFF\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\"><b>");
      out.print(b_filename);
      out.write("</b></font><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"2\" /><br>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th align=\"center\" bgcolor=\"#FFFFFF\" style=\"width: 30%; height: 50px;\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\">전화번호<br></font></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#FFFFFF\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\"><b>");
      out.print(b_phonenum);
      out.write("</b></font><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"2\" /><br>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" bgcolor=\"#FFFFFF\" style=\"height: 600px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"video_preview\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"player\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- vod 재생할때는 이런식으로 주소써야한다. rtmp://192.168.63.33:1935/vod/_definst_/safeme/VID_20151030_203026.mp4 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"stream_url\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"rtmp://192.168.43.23:1935/vod/_definst_/safeme/");
      out.print(b_filename);
      out.write("\" /><br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th align=\"center\" bgcolor=\"#FFFFFF\" style=\"width: 30%; height: 50px;\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\">위도<br></font></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#FFFFFF\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\"><b>");
      out.print(b_loc_lat);
      out.write("</b></font><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"2\" /><br>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th align=\"center\" bgcolor=\"#FFFFFF\" style=\"width: 30%; height: 50px;\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\">경도<br></font></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#FFFFFF\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\"><b>");
      out.print(b_loc_lon);
      out.write("</b></font><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"2\" /><br>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th align=\"center\" bgcolor=\"#FFFFFF\" style=\"width: 30%; height: 50px;\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\">주소<br></font></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#FFFFFF\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-size: 120%\"><b>");
      out.print(b_loc_str);
      out.write("</b></font><br>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<p align=center>\r\n");
      out.write("\t\t<font size=2><a href=sinkokyesipan.jsp>목록으로</a> ");

 	}
 		rs.close();
 		stmt.close();
 		conn.close();
 	} catch (Exception e) {
 		out.println(e);
 	}
 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
